# Default values for ixia-c-b2b.
# Default values for ixia-c-sr.
enabled: true
image1:
  name: te1-svc
image2:
  name: te2-svc
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
serviceAccount:
  create: true
  annotations: {}
  name: ""
securityContext:
  privileged: true
  capabilities:
    add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RAWIO
      - NET_RAW
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
