apiVersion: v2
name: ixia-c
description: |
  description: ixia-c Packet Generation Services
type: application
dependencies:
  - name: ixia-c-b2b
    condition: ixia-c-b2b.enabled
  - name: ixia-c-dise
    condition: ixia-c-dise.enabled
version: 0.1.1
appVersion: 0.0.0