apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.image1.name }}
  labels:
    {{- include "ixia-c-dise.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  {{- if .Values.global }}
  replicas: {{ .Values.global.image1.replicaCount }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ixia-c-dise.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ixia-c-dise.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ixia-c-dise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.global.image1.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.image1.repository }}:{{ .Values.global.image1.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image1.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /docs/
              port: 8080
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /docs/
              port: 8080
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - "--http-port"
            - "8080"
            - "--accept-eula"
            - "--disable-app-usage-reporter"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
